CREATE TABLE SOC (
    ID SERIAL PRIMARY KEY ,
    NOMBRE VARCHAR(150),
    PAIS VARCHAR(150),
    NIVELSEGURIDAD INT ,
    AUTOREXAMEN VARCHAR(150)
);

CREATE TABLE INCIDENTE (
    ID SERIAL PRIMARY KEY ,
    CODIGOINCIDENTE VARCHAR(150) ,
    TIPOINCIDENTE VARCHAR(150) ,
    FECHADETECCION VARCHAR(150),
    ESTADO VARCHAR(150) ,
    SOCID INT NOT NULL,
    AUTOREXAMEN VARCHAR(150),
    CONSTRAINT FK_INCIDENTES_SOC FOREIGN KEY (SOCID) REFERENCES SOC(ID)
);

CREATE TABLE INFORMEINCIDENTE(
    ID SERIAL PRIMARY KEY ,
    MALWAREDETECTADO BOOLEAN,
    NIVELSEVERIDAD INT,
    CONCLUSION VARCHAR(300),
    INCIDENTEID INT NOT NULL UNIQUE ,
    AUTOREXAMEN VARCHAR(150),
    CONSTRAINT FK_INFORME_INCIDENTE FOREIGN KEY (INCIDENTEID) REFERENCES INCIDENTE(ID)
);