INSERT INTO SOC(NOMBRE,PAIS,NIVELSEGURIDAD,AUTOREXAMEN) VALUES ('CASTI', 'Noruega', 30, 'HERNANDEZ_IVAN_DAM2');
INSERT INTO SOC(NOMBRE,PAIS,NIVELSEGURIDAD,AUTOREXAMEN) VALUES ('LASTI', 'España', 50, 'HERNANDEZ_IVAN_DAM3');
INSERT INTO SOC(NOMBRE,PAIS,NIVELSEGURIDAD,AUTOREXAMEN) VALUES ('FASAN', 'Italia', 80 'HERNANDEZ_IVAN_DAM3');
INSERT INTO SOC(NOMBRE,PAIS,NIVELSEGURIDAD,AUTOREXAMEN) VALUES ('PASTEN', 'Brasil', 70, 'HERNANDEZ_IVAN_DAM3');
INSERT INTO SOC(NOMBRE,PAIS,NIVELSEGURIDAD,AUTOREXAMEN) VALUES ('BOVEN', 'Malta', 95, 'HERNANDEZ_IVAN_DAM3');
INSERT INTO SOC(NOMBRE,PAIS,NIVELSEGURIDAD,AUTOREXAMEN) VALUES ('FILI', 'Portugal', 15, 'HERNANDEZ_IVAN_DAM3');

INSERT INTO INCIDENTE(CODIGOINCIDENTE,TIPOINCIDENTE,FECHADETECCION,ESTADO,SOCID,AUTOREXAMEN) VALUES ('1024', 'Informatico', '12/05/2022', 'Activo', 1,'HERNANDEZ_IVAN_DAM3');
INSERT INTO INCIDENTE(CODIGOINCIDENTE,TIPOINCIDENTE,FECHADETECCION,ESTADO,SOCID,AUTOREXAMEN) VALUES ('2367', 'Informatico', '08/03/2026', 'Activo', 2,'HERNANDEZ_IVAN_DAM3');
INSERT INTO INCIDENTE(CODIGOINCIDENTE,TIPOINCIDENTE,FECHADETECCION,ESTADO,SOCID,AUTOREXAMEN) VALUES ('8654', 'Bases', '25/07/2021', 'Inactivo', 3,'HERNANDEZ_IVAN_DAM3');
INSERT INTO INCIDENTE(CODIGOINCIDENTE,TIPOINCIDENTE,FECHADETECCION,ESTADO,SOCID,AUTOREXAMEN) VALUES ('2789', 'Informatico', '12/03/2020', 'Activo', 4,'HERNANDEZ_IVAN_DAM3');
INSERT INTO INCIDENTE(CODIGOINCIDENTE,TIPOINCIDENTE,FECHADETECCION,ESTADO,SOCID,AUTOREXAMEN) VALUES ('1098', 'Bases', '13/09/2021', 'Inactivo', 5,'HERNANDEZ_IVAN_DAM3');
INSERT INTO INCIDENTE(CODIGOINCIDENTE,TIPOINCIDENTE,FECHADETECCION,ESTADO,SOCID,AUTOREXAMEN) VALUES ('5604', 'Bases', '02/01/2022', 'Inactivo', 6,'HERNANDEZ_IVAN_DAM3');


INSERT INTO INFORMEINCIDENTE(ADNPOSITIVO,NIVELRIESGO,CONCLUSION,MUESTRAID,AUTOREXAMEN) VALUES (true, 8, 'Es bastante peligroso',  1,'HERNANDEZ_IVAN_DAM2');
INSERT INTO INFORMEINCIDENTE(ADNPOSITIVO,NIVELRIESGO,CONCLUSION,MUESTRAID,AUTOREXAMEN) VALUES (false, 5, 'Es medio peligroso',  2,'HERNANDEZ_IVAN_DAM2');
INSERT INTO INFORMEINCIDENTE(ADNPOSITIVO,NIVELRIESGO,CONCLUSION,MUESTRAID,AUTOREXAMEN) VALUES (true, 2, 'Es poco peligroso',  3,'HERNANDEZ_IVAN_DAM2');
INSERT INTO INFORMEINCIDENTE(ADNPOSITIVO,NIVELRIESGO,CONCLUSION,MUESTRAID,AUTOREXAMEN) VALUES (false, 3, 'Es poco peligroso', 4,'HERNANDEZ_IVAN_DAM2');
INSERT INTO INFORMEINCIDENTE(ADNPOSITIVO,NIVELRIESGO,CONCLUSION,MUESTRAID,AUTOREXAMEN) VALUES (true, 6, 'Es muy peligroso',  5,'HERNANDEZ_IVAN_DAM2');
INSERT INTO INFORMEINCIDENTE(ADNPOSITIVO,NIVELRIESGO,CONCLUSION,MUESTRAID,AUTOREXAMEN) VALUES (true, 0, 'No es nada peligroso',  6,'HERNANDEZ_IVAN_DAM2');
